name: riman_pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.2'
      - name: Inject local.properties
        run: |
          echo "sdk.dir=${ANDROID_HOME}" > android/local.properties
          echo "flutter.sdk=${FLUTTER_ROOT}" >> android/local.properties
      - name: Build Debug APK
        run: |
          if [ -f "pubspec.yaml" ]; then
            flutter build apk --debug --android-skip-build-dependency-validation
          fi

      - name: Build Release APK
        run: |
          if [ -f "pubspec.yaml" ]; then
            flutter build apk --release --android-skip-build-dependency-validation
          fi
